### ISSUE TITLE
Ambiguous language specification

### ISSUE THREAD

**Issue by xrotwang** [lexibank/bantubvd#1]
In [`raw/6.xml`](https://github.com/lexibank/bantubvd/blob/67ace499f6d1b6906a498724e300bc9777087675/raw/6.xml#L5-L6) the language is listed with two conflicting glottocodes (one in the ISO code field).

**Comment by SimonGreenhill** [comment]
Fixed in a280b2f0c91c3bb18f2135c54ec7ef6dea0ce6d6
